version: '3.8'

services:
  ai-hub:
    image: ai-hub:latest
    container_name: ai-hub
    restart: unless-stopped
    ports:
      - "80:3099"
    volumes:
      - uploads_data:/app/uploads
      - logs_data:/app/logs
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
      - PORT=3099
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3099/api/test"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s
    networks:
      - ai-hub-network

volumes:
  uploads_data:
  logs_data:

networks:
  ai-hub-network:
    driver: bridge